### PR TITLE
Bump parent

### PR DESCRIPTION
**Pull request by jglick**
Compatibility with https://github.com/jenkinsci/jenkins/pull/4944.

### CODE REVIEW

**Comment by jglick** [comment]
CI outage.

**Comment by ikedam** [comment]
Detailed contexts are described in “Inherited private serialization methods” in https://github.com/jenkinsci/jep/pull/309

**Review by ikedam — APPROVED** [review]
Looks good to me.

Should I make a new release to have PCT see this change?
(anyway, there’s a pended minor bug fix #129)

**Comment by jglick** [comment]
> Should I make a new release

If you have the time, I would appreciate it. In the meantime, I am able to test via https://github.com/jenkinsci/plugin-compat-tester/pull/181.

**Comment by ikedam** [comment]
OK., I’ll make a new release this weekend.

**Comment by ikedam** [comment]
Released copyartifact-1.45.2 containing this change.

**Pull request merged**
