### PR TITLE
Add a symbol for BuildSelectorParameter

### PR DESCRIPTION
**Pull request by Vlatombe**
`properties([parameters([buildSelector(name: 'name', description: 'description', defaultSelector: lastCompleted())])])`

instead of

`properties([parameters([$class: 'BuildSelectorParameter', name:'name', description: 'description', defaultSelector:lastCompleted()]])])`

### CODE REVIEW

**Comment by Vlatombe** [comment]
cc @ikedam

**Comment by Vlatombe** [comment]
@ikedam done

**Comment by ikedam** [comment]
Somehow Jenkins reports failure, but there’s no reason this change cause failure.
It looks caused for instability of Windows, and this request is ready to be merged.

**Comment by ikedam** [comment]
Released in copyartifact-1.43. It will be available in the update center in a day.

**Pull request merged**
