### PR TITLE
Configured FindBugs xml output

### PR DESCRIPTION
**Pull request by rsandell**
So Jenkins can pick them up

@reviewbybees

### CODE REVIEW

**Comment by rsandell** [comment]
25 issues found in my initial sweep, too many to fix in my quick drive-by.

**Comment by oleg-nenashev** [comment]
:bee: MOAR findbugs. Was the code clear?

**Comment by ikedam** [comment]
Why didn't Jenkins pick up these 25 issues?

**Comment by rsandell** [comment]
@oleg-nenashev in some places it was clear. But since there was so many I didn't look at them all.

**Comment by rsandell** [comment]
@ikedam I haven't configured the job to run findbugs yet. I wanted to get this in first.

**Comment by stephenc** [comment]
:bee:

**Comment by rsandell** [comment]
@reviewbybees done

**Comment by rsandell** [comment]
@ikedam Are you maintaining this plugin as well? Would it be ok to merge this in so we can start track the findbugs trends, and then when we are down do 0 we could turn on the failing of new warnings.

**Comment by ikedam** [comment]
OK, builds won't fail for existing findbugs warnings, will they?

**Comment by ikedam** [comment]
@rsandell 
Please turn on findbugs feature on Jenkins, and trigger builds twice (to see existing find bugs warnings doesn't cause build failures).

**Pull request merged**
