### PR TITLE
[WIP] [JENKINS-24892] Copyartifact 2.0

### PR DESCRIPTION
**Pull request by ikedam**
[JENKINS-24892](https://issues.jenkins-ci.org/browse/JENKINS-24892)

Refactoring of copyartifact.

New features:
- Build-filter based configuration (https://issues.jenkins-ci.org/browse/JENKINS-24890)
- You can select a "Copy Operation":
  - Copy standard artifact files: copy artifacts from `StandardArtifactManager` (works as before)
  - Copy extended artifact files: copy arftifacts from generic `ArtifactManager` (https://issues.jenkins-ci.org/browse/JENKINS-22637)
    - It doesn't preserver file modes and symbolic links (as `VirtualFile` doesn't provide that feature)
  - Copy files from workspace: works as `WorkspaceSelector` did. (`WorkspaceSelector` is no longer supported)

(Incompatible) changes:
- [`Copier`](https://github.com/jenkinsci/copyartifact-plugin/blob/master/src/main/java/hudson/plugins/copyartifact/Copier.java) is removed.
  - You can extend `CopyArtifactOperation` instead.
- No longer supports `WorkspaceSelector` (https://github.com/jenkinsci/copyartifact-plugin/blob/master/src/main/java/hudson/plugins/copyartifact/WorkspaceSelector.java).
  - You can use `CopyWorkspaceFiles` for `CopyOperation` instead.
- Permission checks are performed only at runtime (https://issues.jenkins-ci.org/browse/JENKINS-24888)

Known issues:
- `VirtualFile` (`ArtifactManager`) doesn't support listing files with ant file patttens (like `**/*.java`) and I had to reimplement it by myself.
  - There can be bugs.
  - There can be performance issues.

This request is still in progress. Left tasks are:
- ~~Make tests passed.~~
- ~~UI: remove `parameters` and handle `BuildFilter`.~~
- ~~Add copy operation abstraction.~~
- ~~Add more `BuildFilter`s including `AndBuildFilter` and `OrBuildFilter`.~~
- ~~Add fallback build selector.~~
- ~~Migrate existing `BuildSelector`s to `BuildFilter`s and support automatic configuration upgrade.~~
- ~~Extend `ParameterizedBuildSelector` to support filters.~~
- ~~Add texts.~~
- Add new tests.

### CODE REVIEW

**Comment by ikedam** [comment]
Many tests fail on Windows as include patterns using "/" don't work.
I'm not sure how Ant's `DirectoryScanner` handles them.

**Comment by ikedam** [comment]
I decided to define "Copy operation" abstract layer, which includes "Copy files from artifacts", "Copy files from legacy artifacts (supports permission, symlinks)", "Copy files from workspace".
Which is the best way to keep the functional compatibility.

**Comment by ikedam** [comment]
Introduced copy operations.

**Comment by ikedam** [comment]
Rebased to 1.38.
Previous branch is at https://github.com/ikedam/copyartifact-plugin/tree/feature/JENKINS-24892_CopyArtifact2.0_1.37based.

**Comment by FransUrbo** [comment]
@ikedam, have you given up on this? How useful is it today, as-is?

**Comment by ikedam** [comment]
@FransUrbo Almost near given up. I don't have time to work for this.
Features in this request is extracted into [Run Selector plugin](https://wiki.jenkins-ci.org/display/JENKINS/Run+Selector+Plugin), and it should make sense to refactor copyartifact to base on run-selector.

**Comment by FransUrbo** [comment]
@ikedam How much work would you guesstimate would take to get this "out the door"? Days, weeks, months? Complete rebuild/refactor against run-selector?

**Comment by ikedam** [comment]
@FransUrbo roughly 5 - 10 days

**Comment by FransUrbo** [comment]
@ikedam This have now escalated into a business problem for us. Would you be interested to finishing of this work in a reasonable time frame (or do you know someone who can/want to) and how much do you think you would want for doing it?

I know you said you don't have time to do it, but is that based on economy or "simply" time and/or interest?

We have a quite nice remaining budget to get our applications "out the door" (and the bugs in the current plugin is seriously having an affect on that), but it's not endless :D

**Comment by ikedam** [comment]
@FransUrbo I'm not sure what cause the buisiness problem, but I have to agree that I don't plan to continue this work (at least, in a reasonable time frame).
You can start your work (or take over this work if you don't mind) and create a new pull request.
I think I can revirew that PR and can contribute to improve that change, or you can take over the maintenance of this plugin if you don't mind it (please contact jenkinsci-dev mailing list).

> but is that based on economy or "simply" time and/or interest?

All of them.
I'm busy for my other works, and I myself don't have serious problems in copyartifact-1.x.

**Comment by FransUrbo** [comment]
@ikedam I don't "speak" java unfortunately, and all our Java devels are busy with getting our applications out the door :(.

To all lurkers: If anyone thinks they are up to the task, there is an financial incentive available to finish this of.

@ikedam If you know of anyone that might be able to do this (and have the time/interest :), please feel free to send this over to them.

PS. The problem we're having with the current module is that it
1) doesn't copy ALL artefacts - as in, there's artefact(s) missing.
2) copies only PART of the artefact(s) - as in, they're broken after copy.

**Comment by ikedam** [comment]
Gave up.
See following for more details:
* https://groups.google.com/d/msg/jenkinsci-dev/2kbMx_wDSbA/6C0Sr2eVDQAJ

**Pull request closed without merging**
