### PR TITLE
fixes JENKINS-18938 when setting COPYARTIFACT_BUILD_NUMBER_<job> don'…

### PR DESCRIPTION
**Pull request by GeekOffTheStreet**
…t replace numbers in job name

### CODE REVIEW

**Comment by ikedam** [comment]
I agree the current behavior is bad.
But I don't think to merge this request as:
* This change might break existing setups.
* The mapping from project names to variable names are complicated and it's not easy for users to know the variable name they need, even with this change.

How about adding a new field to specify the variable name to hold the build number?

**Comment by jdmears2** [comment]
Without a doubt, the change is not backwards compatible for anyone currently utilizing the variable for a job with a number in it.

With respect to your second bullet, yes the renaming is confusing.  However, this change would put the behavior of this plugin in line with the parameterized build plugin: https://wiki.jenkins-ci.org/display/JENKINS/Parameterized+Trigger+Plugin

I'm not sure I understand your last sentence.  Are you suggesting a completely new environment variable for each job?

**Comment by ikedam** [comment]
Like this.
copyartifact-buildnumbervariable

**Comment by ikedam** [comment]
merged #69 instead.

**Pull request closed without merging**
