### PR TITLE
Provide a Jenkinsfile build/testing on ci.jenkins.io

### PR DESCRIPTION
**Pull request by rtyler**
buildPlugin() provided by: https://github.com/jenkins-infra/pipeline-library

### CODE REVIEW

**Comment by ikedam** [comment]
I don't know why tests failed, but this change looks perfect and ready to merge.
Failures should be handled as another issue.

**Comment by ikedam** [comment]
Hmm... I couldn't merge with "Pull requests that have a failing status can’t be merged on a phone."

**Comment by rtyler** [comment]
@ikedam No worries, I hit the merge.

**Comment by ikedam** [comment]
Thanks!
Tests look failed for windows environment, and I'll fix that by having tests not to depend on OS environment.

**Comment by jglick** [comment]
@rtyler no!!! The whole point of filing a `Jenkinsfile` addition as a PR is that you get all the tests passing, incl. on Windows, _before_ merging, so that other PRs show a fair status.

**Comment by ikedam** [comment]
Sorry, that sounds rather my fault...
I didn't think this affects also existing pull requests.
Fixes for tests are now in progress in #90 .

**Pull request merged**
