### PR TITLE
Use parent pom 4.77

### PR DESCRIPTION
**Pull request by shivajee98**
mvn versions:update-parent
Added null check in CopyArtifact.java and handle IllegalArgumentException
#### Testing Details:

- [x] Automated tests executed successfully.
- [x] Cloud build performed using `mvn clean install` on Codesapce

```[tasklist]
### Submitter checklist
- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did

### CODE REVIEW

**Review by MarkEWaite — CHANGES_REQUESTED** [review]
Please remove the `pom.xml.versionsBackup` file.  It is not needed and will distract others.

**Comment by shivajee98** [comment]
> Please remove the `pom.xml.versionsBackup` file. It is not needed and will distract others.

ok

**Comment by MarkEWaite** [comment]
Please retain the pull request template, including the `Testing Done` heading.  Below the `Testing Done` heading, describe how you verified that the change is correct.

The pull request template means it when it says:

### Testing done

Provide a clear description of how this change was tested.
At minimum this should include proof that a computer has executed the changed lines.
Ideally this should include an automated test or an explanation as to why this change has no tests.
Note that automated test coverage is less than complete, so a successful PR build does not necessarily imply that a computer has executed the changed lines.
If automated test coverage does not exist for the lines you are changing, you must describe the scenario(s) in which you manually tested the change.
For frontend changes, include screenshots of the relevant page(s) before and after the change.
For refactoring and code cleanup changes, exercise the code before and after the change and verify the behavior remains the same.

**Review by MarkEWaite — CHANGES_REQUESTED** [review]
@shivajee98 I told you in the earlier review of the pull request to split the pull request into multiple pull requests.  You've again combined multiple changes into a single pull request.  Please don't do that.  It  makes the change more difficult to review and makes the maintainer less likely to accept the change.

**Comment by shivajee98** [comment]
> @shivajee98 I told you in the earlier review of the pull request to split the pull request into multiple pull requests. You've again combined multiple changes into a single pull request. Please don't do that. It makes the change more difficult to review and makes the maintainer less likely to accept the change.

While code was going through the checks then SpotBugs identified issue of null exception, so i made the change here
I am trying to clear that

**Comment by MarkEWaite** [comment]
> While code was going through the checks then SpotBugs identified issue of null exception, so i made the change here I am trying to clear that

That makes sense.  Thanks for the clarification.

**Review by MarkEWaite — CHANGES_REQUESTED** [review]
Please remove the IDE settings file `.vscode/settings.json` from the pull request.  That setting is specific to your IDE and is unrelated to the topic of the pull request.

**Comment by MarkEWaite** [comment]
Please add a "Testing done" section to the pull request description and describe the testing you used to confirm this change is correct and complete.

**Comment by shivajee98** [comment]
> Please add a "Testing done" section to the pull request description and describe the testing you used to confirm this change is correct and complete.

Ok sure

**Comment by MarkEWaite** [comment]
I made some style changes in 02e1fb39d2b5822e93af6f14d6bdef5b11041c24 because I prefer to define the variable near its use so that it is clear that the variable `i` is only being used in that branch of the conditional.

I made some spacing changes in 02e1fb39d2b5822e93af6f14d6bdef5b11041c24 because I like to keep the number of changes small between versions.

I did those myself rather than bothering you with them because they are purely questions of style and this plugin does not have a contributing guide that offers an opinion on those questions of style.

Are those changes acceptable to you @shivajee98 ?  If so, then once the CI job passes, I believe this is ready to be squash merged.

**Review by MarkEWaite — APPROVED** [review]
Thanks.

Since the previous behavior with a null projectName would have been to throw a null pointer exception, I think it is OK to throw an illegal argument exception.

**Pull request merged**
