### PR TITLE
Require minimum Jenkins 2.414.3

### PR DESCRIPTION
**Pull request by jonesbusy**
Hi,

Latest release is pulling deprecated dependencies (see bellow)

```
copyartifact depends on:
matrix-project 802.v8013b_40c7edc
```

```
matrix-project depends on:
junit 1189.v1b_e593637fa_e
...
```

```
junit depends on:
bootstrap5-api 5.2.1-3
...
```

```
bootstrap5-api depends on:
font-awesome-api 6.2.0-3
popper2-api 2.11.6-1 <-- This is deprecated and don't want this
```

A release will be appreciated

### Testing done

Only automated tests

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by jonesbusy** [comment]
I think it's also some issues of the plugin-installation manager.

I have all plugins installed to latest version (but I'm installing copyartifact afterward. Because popper2-api is not anymore installed on my instance (no plugin depends anymore on it) copartifact still pull it

```
Will install new plugin popper2-api 2.11.6-1
Will install new plugin copyartifact 722.v0662a_9b_e22a_c
Will use url: https://<internal repo>/artifactory/<repo>/download/plugins/copyartifact/722.v0662a_9b_e22a_c/copyartifact.hpi to download copyartifact plugin
Will use url: https://<internal repo>/artifactory/<repo>/download/plugins/popper2-api/2.11.6-1/popper2-api.hpi to download popper2-api plugin
```

**Review by MarkEWaite — APPROVED** [review]
Thanks!

**Comment by MarkEWaite** [comment]
I don't think that a new release of the copyartifact plugin will solve the issue that you are seeing.  The issue is in the plugin installation manager and the arguments that you are passing to it.

I use a [plugins.txt file](https://github.com/MarkEWaite/docker-lfs/blob/b0b737b7b1c4eeb33e694f5f5ef42e4dc92ef4c5/plugins.txt#L11) that lists the precise version of every plugin that is to be installed so that I don't rely on the plugin installation manager tool to resolve transitive dependencies.  That avoids the problem because in my list of plugins I have `bootstrap5-api:5.3.3-1` rather than the older dependency that is declared by the junit plugin.

An issue has been reported for the plugin installation manager tool, but I'm not sure that there is a viable, compatible solution for it without adding a new mode or a new set of options.  See the issue at:

* https://github.com/jenkinsci/plugin-installation-manager-tool/issues/628

**Comment by jonesbusy** [comment]
Hi,

I have 2 steps installation (list of plugin on a base image) and then extra plugin installed via the jenkins helm chart

```
installPlugins:
   - copyartifact:722.v0662a_9b_e22a_c
```

Well at the end I was able to workaround the issue be "reinstalling" the bootstrap5-api

```
        installPlugins:
        - copyartifact:722.v0662a_9b_e22a_c
        - bootstrap5-api:5.3.3-1
```

But yes the point is that the plugin installation manager is doing the dependency resolution based in the inputs (plugin.txt or CLI) and not what is actually installed already on the instance. It can cause that a plugin is installed when it shouldn't

**Pull request merged**
