### PR TITLE
Using RobustHTTPClient utility for artifact downloads

### PR DESCRIPTION
**Pull request by jglick**
Picks up https://github.com/jenkinsci/apache-httpcomponents-client-4-api-plugin/pull/9 so that network problems need not be fatal. Follows up #100.

### CODE REVIEW

**Comment by jglick** [comment]
> Will the annotation be removed

Not that quickly, no.

> it looks succeed even without `useBeta=true` for `apache-httpcomponents-client-4-api-plugin`

The property is set on the plugin _consuming_ the beta API.

**Comment by ikedam** [comment]
> > it looks succeed even without useBeta=true for apache-httpcomponents-client-4-api-plugin
> The property is set on the plugin consuming the beta API.

Oh, I see. I misunderstood that.

It looks annotated as beta for `VirtualFile#toExternalURL` is beta.
https://github.com/jenkinsci/jenkins/blob/jenkins-2.121/core/src/main/java/jenkins/util/VirtualFile.java#L352

**Comment by jglick** [comment]
@ikedam do you have a plan to release this? https://github.com/jenkinsci/jenkins/pull/3480 remains on hold until then.

**Comment by ikedam** [comment]
@jglick
I plan to make a new release after resolving #105.

**Comment by ikedam** [comment]
@jglick I released copyartifact-1.41 with this change.

**Pull request merged**
