### PR TITLE
JENKINS-64189 Fix plugin on Jenkins > 2.263

### PR DESCRIPTION
**Pull request by timja**
https://issues.jenkins.io/browse/JENKINS-64189

### CODE REVIEW

**Comment by ikedam** [comment]
Oh, I see what happened. Thanks.

The new code looks complicated.
How about using form:invisibleEntry?

https://github.com/jenkinsci/jenkins/blob/jenkins-2.263/core/src/main/resources/lib/form/invisibleEntry.jelly
https://github.com/jenkinsci/jenkins/blob/jenkins-2.264/core/src/main/resources/lib/form/invisibleEntry.jelly

**Comment by timja** [comment]
yeah that looks better

**Review by ikedam — APPROVED** [review]
Thanks!
I’ll make a new release soon.

**Comment by ikedam** [comment]
Works correct with:
* 2.249.3 (latest LTS)
* 2.263
* 2.264
* 2.268 (latest)

**Pull request merged**
